name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: input
    id: email
    attributes:
      label: Email Address
      description: So we can follow up with you
      placeholder: your@email.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see
      placeholder: I'd like to be able to...
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      placeholder: e.g. 1.0.3
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: e.g. iPhone 15 Pro, Pixel 8
    validations:
      required: false
  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: e.g. iOS 18.4, Android 15
    validations:
      required: false
