import XCTest
@testable import AdagioStream

final class SubsonicAuthTests: XCTestCase {

    // MARK: - Spec test vector

    /// Canonical Subsonic example from the protocol spec:
    /// password "sesame" + salt "c19b2d" => t == "26719a1196d2a940705a59634eb18eab"
    func testSpecTestVector() {
        let token = SubsonicAuth.md5Token(password: "sesame", salt: "c19b2d")
        XCTAssertEqual(token, "26719a1196d2a940705a59634eb18eab",
                       "MD5(password+salt) must match the canonical Subsonic spec example")
    }

    // MARK: - queryItems content

    func testQueryItemsContainAllRequiredFields() {
        let auth = SubsonicAuth(username: "alice", password: "sesame")
        let items = auth.queryItems(salt: "c19b2d")

        XCTAssertEqual(value(for: "u", in: items), "alice")
        XCTAssertEqual(value(for: "t", in: items), "26719a1196d2a940705a59634eb18eab")
        XCTAssertEqual(value(for: "s", in: items), "c19b2d")
        XCTAssertEqual(value(for: "c", in: items), SubsonicAuth.clientName)
        XCTAssertEqual(value(for: "v", in: items), SubsonicAuth.apiVersion)
        XCTAssertEqual(value(for: "f", in: items), "json")
        XCTAssertEqual(items.count, 6)
    }

    func testClientNameConstant() {
        XCTAssertEqual(SubsonicAuth.clientName, "AdagioStream")
    }

    func testApiVersionConstant() {
        XCTAssertEqual(SubsonicAuth.apiVersion, "1.16.1")
    }

    // MARK: - Determinism

    func testSamePasswordSameSaltProducesSameToken() {
        let auth = SubsonicAuth(username: "bob", password: "hunter2")
        let items1 = auth.queryItems(salt: "abc123")
        let items2 = auth.queryItems(salt: "abc123")

        XCTAssertEqual(value(for: "t", in: items1), value(for: "t", in: items2),
                       "Same password+salt must always produce the same token")
    }

    // MARK: - Different salts produce different tokens

    func testDifferentSaltsProduceDifferentTokens() {
        let auth = SubsonicAuth(username: "carol", password: "mypassword")
        let items1 = auth.queryItems(salt: "saltalpha")
        let items2 = auth.queryItems(salt: "saltbeta")

        XCTAssertNotEqual(value(for: "t", in: items1), value(for: "t", in: items2),
                          "Different salts must produce different tokens")
        XCTAssertNotEqual(value(for: "s", in: items1), value(for: "s", in: items2),
                          "Different salts must appear as different s params")
    }

    // MARK: - Random salt generation

    func testAutoGeneratedSaltIsNonEmpty() {
        let auth = SubsonicAuth(username: "dave", password: "pass")
        let items = auth.queryItems()

        let salt = value(for: "s", in: items)
        XCTAssertNotNil(salt)
        XCTAssertFalse(salt!.isEmpty, "Auto-generated salt must not be empty")
    }

    func testAutoGeneratedSaltIsReasonablyLong() {
        let auth = SubsonicAuth(username: "eve", password: "pass")
        let items = auth.queryItems()

        // 12 bytes → 24 hex chars; we require at least 16 (8 bytes minimum)
        let salt = value(for: "s", in: items) ?? ""
        XCTAssertGreaterThanOrEqual(salt.count, 16,
                                    "Salt must be at least 16 hex characters (≥8 bytes)")
    }

    func testTwoAutoGeneratedSaltsAreDifferent() {
        let auth = SubsonicAuth(username: "frank", password: "pass")
        let items1 = auth.queryItems()
        let items2 = auth.queryItems()

        let salt1 = value(for: "s", in: items1)
        let salt2 = value(for: "s", in: items2)
        XCTAssertNotEqual(salt1, salt2, "Two independently generated random salts should differ")
    }

    // MARK: - Password not in description / debugDescription

    func testPasswordAbsentFromDescription() {
        let auth = SubsonicAuth(username: "grace", password: "s3cr3t!")
        XCTAssertFalse(auth.description.contains("s3cr3t!"),
                       "Password must not appear in description")
    }

    func testPasswordAbsentFromDebugDescription() {
        let auth = SubsonicAuth(username: "grace", password: "s3cr3t!")
        XCTAssertFalse(auth.debugDescription.contains("s3cr3t!"),
                       "Password must not appear in debugDescription")
    }

    // MARK: - Helpers

    private func value(for name: String, in items: [URLQueryItem]) -> String? {
        items.first(where: { $0.name == name })?.value
    }
}
